# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8001

spring:
  application:
    name: csrp-provider
  profiles:
    active: dev
# mybatis
mybatis:
  mapper-locations: classpath*:com/york/**/mapper/*.xml
  type-aliases-package: org.csrp.cloud.entity
