# Eureka注册中心配置
# 多数据源配置
spring:
 application:
  name: csrp-provider
 cloud:
  zookeeper:
    # 注册到zookeeper地址
   connect-string: localhost:2181
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password: 123456
  url: jdbc:mysql://localhost:3306/shard_one?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
  druid:
   max-active: 50
   max-wait: 60000
   initial-size: 5
   min-idle: 1
   pool-prepared-statements: true
   max-open-prepared-statements: 20
   validation-query: select 1 from dual
   test-on-borrow: false
   test-on-return: false
   test-while-idle: true
   time-between-eviction-runs-millis: 120000
   remove-abandoned: true
   remove-abandoned-timeout: 180
   log-abandoned: true
