# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9001

spring:
  application:
    name: csrp-cumster
  profiles:
    active: dev

ribbon:
  eureka:
    enable: true


